name: Build and Deploy
on: 
  push:
    branches:
    - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Deno
      uses: denolib/setup-deno@master
      with:
        deno-version: 1.10.2
    - name: Run script
      run: deno run script.ts
    - name: Action deploy
      uses: bumfo/action-deploy@v1
      with:
        ref: 'refs/heads/release/snapshot'  # The branch to auto deploy, default to release/snapshot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # - name: Deploy documentation
    #   if: success()
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./src/.vuepress/dist
    #     commit_message: ${{ github.event.head_commit.message }}
    #     cname: devartsite.github.io/dftps-guide/
    #     keep_files: true
    #     enable_jekyll: false
