name: Build and Deploy
on: 
  push:
    branches:
    - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Deno
      uses: denolib/setup-deno@master
      with:
        deno-version: v1.x
    - name: Compile script
      run: deno compile script.ts
    - name: Zip script
      run: zip script script
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: script.zip
        body_path: ${{ github.workflow }}-CHANGELOG.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: devartsite/deploy
