name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Deno
      run: curl -fsSL https://deno.land/x/install/install.sh | sh
    - name: Run script
      run: |
        ./$HOME/.deno/bin/deno run script.ts
    # - name: Deploy documentation
    #   if: success()
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./src/.vuepress/dist
    #     commit_message: ${{ github.event.head_commit.message }}
    #     cname: devartsite.github.io/dftps-guide/
    #     keep_files: true
    #     enable_jekyll: false
